config/routes.rb
Rails.application.routes.draw do
    resources :projects do
        collection do
            get 'search'
        end
        resources :applies, only: [:new, :create]
    end
    devise_for :users

  get "pages/about"
  get "pages/contact"
  get 'programmer' => "projects#programmer"
  get 'employer' => "projects#employer"
  get 'interested_projects' => "applies#interested_projects"
  get 'employees' => "applies#employees"

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
    validates :free_time, :skills, presence: true

    belongs_to :project
    belongs_to :interested, class_name: "User"
    belongs_to :employer, class_name: "User"
end

app/models/project.rb
class Project < ApplicationRecord
    has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "no-image-found.jpg"

    searchkick

    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    validates :name, :skill, presence: true

    belongs_to :user
    has_many :applies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :projects, dependent: :destroy
 has_many :employees, class_name: "Apply", foreign_key: "employer_id"
 has_many :interested_projects, class_name: "Apply", foreign_key: "interested_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:category])
        devise_parameter_sanitizer.permit(:account_update, keys: [:category])
    end
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :set_apply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def employees
      @applies = Apply.all.where(employer: current_user).order("created_at DESC")
  end

  def interested_projects
      @applies = Apply.all.where(interested: current_user).order("created_at DESC")
  end

  # GET /applies/1
  # GET /applies/1.json
  def show
  end

  # GET /applies/new
  def new
    @apply = Apply.new
    @project = Project.find(params[:project_id])
  end

  # POST /applies
  # POST /applies.json
  def create
    @apply = Apply.new(apply_params)
    @project = Project.find(params[:project_id])
    @employer = @project.user

    @apply.project_id = @project.id
    @apply.interested_id = current_user.id
    @apply.employer_id = @employer.id
    respond_to do |format|
      if @apply.save
        format.html { redirect_to root_url, notice: 'Apply was successfully created.' }
        format.json { render :show, status: :created, location: @apply }
      else
        format.html { render :new }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apply
      @apply = Apply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apply_params
      params.require(:apply).permit(:free_time, :skills)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:programmer, :new, :create, :edit, :update, :destroy]
    before_action :check_user, only: [:edit, :update, :destroy]
    # GET /projects
    # GET /projects.json

    def programmer
        @projects = Project.where(user: current_user).order("created_at DESC")
    end

    def search
        if params[:search].present?
            @projects = Project.search(params[:search])
        else
            @projects = Project.all
        end
    end

    def index
        @projects = Project.all.order("created_at DESC")
    end

    # GET /projects/1
    # GET /projects/1.json
    def show
    end

    # GET /projects/new
    def new
        @project = Project.new
    end

    # GET /projects/1/edit
    def edit
    end

    # POST /projects
    # POST /projects.json
    def create
        @project = Project.new(project_params)
        @project.user_id = current_user.id

        respond_to do |format|
            if @project.save
                format.html { redirect_to @project, notice: 'Project was successfully created.' }
                format.json { render :show, status: :created, location: @project }
            else
                format.html { render :new }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /projects/1
    # PATCH/PUT /projects/1.json
    def update
        respond_to do |format|
            if @project.update(project_params)
                format.html { redirect_to @project, notice: 'Project was successfully updated.' }
                format.json { render :show, status: :ok, location: @project }
            else
                format.html { render :edit }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /projects/1
    # DELETE /projects/1.json
    def destroy
        @project.destroy
        respond_to do |format|
            format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
        @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
        params.require(:project).permit(:name, :company, :description, :skill, :peopleWorking, :peopleNeeded, :location, :image)
    end

    def check_user
        if current_user != @project.user
            redirect_to root_url, alert: "Sorry, this project belongs to someone else!"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/applies/_form.html.erb
<%= form_for([@project, @apply]) do |f| %>
  <% if apply.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(apply.errors.count, "error") %> prohibited this apply from being saved:</h4>

      <ul>
      <% apply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :free_time %>
    <%= f.number_field :free_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :skills %>
    <%= f.text_field :skills, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Apply", class: "btn btn-success" %>
  </div>
<% end %>

app/views/applies/employees.html.erb
<div class ="center">
    <h2> People Interested In Your Projects: </h2>
</div>

<table class= "table table-striped table-bordered">
    <tr>
        <th class="center"> Image</th>
        <th class="center"> Project</th>
        <th class="center"> Skill</th>
        <th class="center"> Person Interested</th>
        <th class="center"> Date Of Apply</th>
    </tr>


        <% @applies.each do |apply| %>
        <tr>
            <td class="center"><%= image_tag apply.project.image.url(:thumb) %></td>
            <td class="center"><%= apply.project.name %></td>
            <td class="center"><%= apply.project.skill %></td>
            <td class="center"><%= apply.interested.name %></td>
            <td class="center"><%= apply.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
        <% end %>
</table>

app/views/applies/interested_projects.html.erb
<div class ="center">
    <h2> Projects You're Interested In: </h2>
</div>

<table class= "table table-striped table-bordered">
    <tr>
        <th class="center"> Image</th>
        <th class="center"> Project</th>
        <th class="center"> Skill</th>
        <th class="center"> Project Owner</th>
        <th class="center"> Date Of Apply</th>
    </tr>


        <% @applies.each do |apply| %>
        <tr>
            <td class="center"><%= image_tag apply.project.image.url(:thumb) %></td>
            <td class="center"><%= apply.project.name %></td>
            <td class="center"><%= apply.project.skill %></td>
            <td class="center"><%= apply.employer.name %></td>
            <td class="center"><%= apply.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
        <% end %>
</table>

app/views/applies/new.html.erb
<h1>New Apply</h1>

<%= render 'form', apply: @apply %>

<%= link_to 'Back', project_applies_path %>

app/views/layouts/_facebooklike.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=1111417615643486";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<a>Copyright 2017, Gabriel Ziegler & Joao Carlos</a>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">DevFinder</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/pages/about">About <span class="sr-only">(current)</span></a></li>
                <li><a href="/pages/contact">Contact</a></li>
            </ul>
            <%= form_tag search_projects_path, method: :get, class: "navbar-form navbar-left" do %>
            <p>
                <%= text_field_tag :search, params[:search], class: "form-control" %>
                <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
            </p>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                <li><%= link_to "People Interested", employees_path%></li>
                <li><%= link_to "Interested Projects", interested_projects_path%></li>
                <li><%= link_to "Manage Projects", programmer_path%></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete%></li>
                <% else %>
                <li><%= link_to "Sign up", new_user_registration_path%></li>
                <li><%= link_to "Sign in", new_user_session_path%></li>
                <% end %>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/png" href="/assets/logo.png">
    <title>DevFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/facebooklike'%>
    <%= render 'layouts/header'%>

    <div class="container">
        <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class=
                "sr-only">Close</spar></button>
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
            <% end %>
            <% end %>

            <%= yield %>

            <%= render 'layouts/footer'%>
        </div>
    </body>
    </html>

app/views/pages/about.html.erb
<div>
<center>
<h2 >About</h2>
<br></br>
<center>
</div>
<html>
<body>


<table style="width:100%">
  <tr>
    <th><h2>Programmer</h2></th>
    <th><h2> </h2></th>
    <th><h2>Project</h2></th>
  </tr>
</table>
<div><br><img src="https://scontent.fbsb8-2.fna.fbcdn.net/v/t1.0-9/13775634_1118248958242254_6689876213056701734_n.jpg?oh=8431dde9592ba3f98bf7bffcc16d20e7&oe=5A0D632C" alt="Gabriel" style="width:304px;height:228px;">
  <img src="https://image.freepik.com/fotos-gratis/laptop-aberto-na-mesa-velha-de-madeira_426-19315259.jpg" alt="project" style="float:right;width:700px;height:368px;">
</div>
</br>
<li>Gabriel Ziegler Programador/Estudante</li>
<li>Cursando Engenharia de Software </li>
<li>Universidade de Brasilia - FGA</li>
</body>
</html><html>
<body>

<h2>Programmer</h2>
<br><img src="https://scontent.fbsb8-2.fna.fbcdn.net/v/t1.0-9/10734170_716961671723449_8198802727862755347_n.jpg?oh=226caf924594cedda2c1641428e0f230&oe=59DC4929" alt="Joao" style="width:304px;height:228px;">
</br>
<li>Joao Carlos Porto Programador/Estudante</li>
<li>Cursando Engenharia de Software </li>
<li>Universidade de Brasilia - FGA</li>
<br></br>
</body>
</html>

app/views/pages/contact.html.erb
<h2>Programmer</h2>
<br><img src="https://scontent.fbsb8-2.fna.fbcdn.net/v/t1.0-9/13775634_1118248958242254_6689876213056701734_n.jpg?oh=8431dde9592ba3f98bf7bffcc16d20e7&oe=5A0D632C" alt="Gabriel" style="width:304px;height:228px;">

</br>
<br><A href="https://mail.google.com/mail/u/0/#inbox?compose=new" title="Email" target="_blank">Email: </A>gabrielziegler3@gmail.com</br>
<A href="https://www.facebook.com/gabriel.ziegler1" title="Email" target="_blank">Facebook</A>

</body>
</html><html>
<body>

<h2>Programmer</h2>
<br><img src="https://scontent.fbsb8-2.fna.fbcdn.net/v/t1.0-9/10734170_716961671723449_8198802727862755347_n.jpg?oh=226caf924594cedda2c1641428e0f230&oe=59DC4929" alt="Joao" style="width:304px;height:228px;">
</br>
<br><A href="https://mail.google.com/mail/u/0/#inbox?compose=new" title="Email" target="_blank">Email: </A>joao4018@gmail.com</br>
<A href="https://www.facebook.com/profile.php?id=100002288680439" title="Facebook" target="_blank">Facebook</A>

<br></br>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project, html: { multipart: true }) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company %>
    <%= f.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :skill %>
    <%= f.text_field :skill, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :peopleWorking %>
    <%= f.number_field :peopleWorking, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :peopleNeeded %>
    <%= f.number_field :peopleNeeded, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project, class: "btn btn-link" %> |
<%= link_to 'Back', projects_path, class: "btn btn-link" %>

app/views/projects/index.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
    <br><br>
<% end %>
<div class ="center">
    <div class="row">
        <% @projects.each do |project| %>
        <div class="col-md-3">
            <div class="thumbnail">
                <%= link_to image_tag(project.image.url(:medium)), project %>
                <div class="caption">
                    <h3><%= project.name %></h3>
                    <p><%= "Company: " + project.company %></p>
                    <p><%= "Skill: " + project.skill %></p>
                    <p><%= "Group Size: " + project.peopleWorking.to_s %></p>
                    <p><%= "Members Needed: " + project.peopleNeeded.to_s %></p>
                    <p><%= "Location: " + project.location.to_s %></p>
                    <p><%= "Project Owner: " + project.user.name.to_s %></p>
                    <% if (user_signed_in?) && (current_user == project.user) %>
                        <%= link_to 'Edit', edit_project_path(project), class: "btn btn-link" %>
                        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

<br>


<br><br><br>

<div class="fb-like" data-href="http://localhost:3000/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, class: "btn btn-link" %>

app/views/projects/programmer.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
    <br><br>
<% end %>
<div class ="center">
    <div class="row">
        <% @projects.each do |project| %>
        <div class="col-md-3">
            <div class="thumbnail">
                <%= link_to image_tag(project.image.url(:medium)), project %>
                <div class="caption">
                    <h3><%= project.name %></h3>
                    <p><%= "Company: " + project.company %></p>
                    <p><%= "Skill: " + project.skill %></p>
                    <p><%= "Group Size: " + project.peopleWorking.to_s %></p>
                    <p><%= "Members Needed: " + project.peopleNeeded.to_s %></p>
                    <p><%= "Location: " + project.location.to_s %></p>
                    <p><%= "Project Owner: " + project.user.name.to_s %></p>
                    <% if (user_signed_in?) && (current_user == project.user) %>
                        <%= link_to 'Edit', edit_project_path(project), class: "btn btn-link" %>
                        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

<br>


<br><br><br>

<div class="fb-like" data-href="http://localhost:3000/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

app/views/projects/search.html.erb
<div class ="center">
    <div class="row">
        <% @projects.each do |project| %>
        <div class="col-md-3">
            <div class="thumbnail">
                <%= link_to image_tag(project.image.url(:medium)), project %>
                <div class="caption">
                    <h3><%= project.name %></h3>
                    <p><%= "Company: " + project.company %></p>
                    <p><%= "Skill: " + project.skill %></p>
                    <p><%= "Group Size: " + project.peopleWorking.to_s %></p>
                    <p><%= "Members Needed: " + project.peopleNeeded.to_s %></p>
                    <p><%= "Location: " + project.location.to_s %></p>
                    <p><%= "Project Owner: " + project.user.name.to_s %></p>
                    <% if (user_signed_in?) && (current_user == project.user) %>
                        <%= link_to 'Edit', edit_project_path(project), class: "btn btn-link" %>
                        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/projects/show.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="thumbnail">
        <%= image_tag @project.image.url(:medium) %>
        </div>
    </div>
    <div class="col-md-6">
        <h3><%= @project.name %></h3><br>
        <p><%= "Company: " + @project.company %></p>
        <p><%= "Skill: " + @project.skill %></p>
        <p><%= "Group Size: " + @project.peopleWorking.to_s %></p>
        <p><%= "Members Needed: " + @project.peopleNeeded.to_s %></p>
        <p><%= "Location: " + @project.location.to_s %></p>
        <br><br><br><br>
        <p><%= "Description: " + @project.description %></p>
        <br>
        <div class= "center">
            <% if current_user != @project.user %>
                <%= link_to "Apply Now", new_project_apply_path(@project), class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

<iframe
    width="300"
    height="300"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC7gtYar38cLwRz8RTuBQN_4od8biPmTvI
    &q= <%= @project.location.parameterize %>" allowfullscreen>
</iframe>

<br><br><br>
<% if current_user == @project.user %>
    <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', projects_path, class: "btn btn-link" %>
<br>